command:
  - /bin/bash
  - -c
  - streamlit run app.py --server.port $PORT

env:
  LAKEBASE_HOST: "${secrets/lakebase-secrets/lakebase-host}"
  LAKEBASE_PORT: "5432"
  LAKEBASE_DATABASE: databricks_postgres
  LAKEBASE_USER: ticket-app-role
  LAKEBASE_PASSWORD: "${secrets/lakebase-secrets/lakebase-password}"